
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (36,  'Value',	10	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (37,  'Value',	11	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (38,  'Value',	12	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (39,  'Value',	13	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (40,	'Definitely not purchase it',	14,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (41,	'Probably not purchase it',	14,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (42,	'Might or might not purchase it',	14,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (43,	'Probably purchase it',	14,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (44,	'Definitely purchase it',	14,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (45,	'Definitely not purchase it',	15,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (46,	'Probably not purchase it',	15,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (47,	'Might or might not purchase it',	15,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (48,	'Probably purchase it',	15,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (49,	'Definitely purchase it',	15,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (50,	'Limited Value',	16,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (51,	'.',	16,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (52,	'.',	16,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (53,	'.',	16,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (54,	'.',	16,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (55,	'.',	16,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (56,	'.',	16,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (57,	'.',	16,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (58,	'.',	16,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (59,	'Highly Valuable',	16,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (60,	'Limited Value',	17,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (61,	'.',	17,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (62,	'.',	17,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (63,	'.',	17,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (64,	'.',	17,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (65,	'.',	17,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (66,	'.',	17,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (67,	'.',	17,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (68,	'.',	17,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (69,  'Highly Valuable',	17,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (70,  'Numeric',	18	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (71,  'Value',	19	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (72,  'Value',	20	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (73,  'Value',	21	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (74,  'Value',	22	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (75,	'Definitely not purchase it',	23,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (76,	'Probably not purchase it',	23,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (77,	'Might or might not purchase it',	23,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (78,	'Probably purchase it',	23,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (79,	'Definitely purchase it',	23,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (80,	'Definitely not purchase it',	24,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (81,	'Probably not purchase it',	24,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (82,	'Might or might not purchase it',	24,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (83,	'Probably purchase it',	24,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (84,	'Definitely purchase it',	24,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (85,	'Limited Value',	25,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (86,	'.',	25,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (87,	'.',	25,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (88,	'.',	25,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (89,	'.',	25,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (90,	'.',	25,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (91,	'.',	25,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (92,	'.',	25,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (93,	'.',	25,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (94,	'Highly Valuable',	25,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (95,	'Limited Value',	26,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (96,	'.',	26,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (97,	'.',	26,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (98,	'.',	26,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (99,	'.',	26,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (100,	'.',	26,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (101,	'.',	26,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (102,	'.',	26,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (103,	'.',	26,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (104,  'Highly Valuable',	26,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (105,  'Numeric',	27	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (106,  'Value',	28	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (107,  'Value',	29	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (108,  'Value',	30	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (109,  'Value',	31	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (110,	'Definitely not purchase it',	32,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (111,	'Probably not purchase it',	32,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (112,	'Might or might not purchase it',   32,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (113,	'Probably purchase it',	32,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (114,	'Definitely purchase it',	32,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (115,	'Definitely not purchase it',	33,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (116,	'Probably not purchase it',	33,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (117,	'Might or might not purchase it',	33,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (118,	'Probably purchase it',	33,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (119,	'Definitely purchase it',	33,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (120,	'Limited Value',	34,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (121,	'.',	34,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (122,	'.',	34,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (123,	'.',	34,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (124,	'.',	34,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (125,	'.',	34,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (126,	'.',	34,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (127,	'.',	34,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (128,	'.',	34,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (129,	'Highly Valuable',	34,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (130,	'Limited Value',	35,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (131,	'.',	35,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (132,	'.',	35,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (133,	'.',	35,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (134,	'.',	35,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (135,	'.',	35,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (136,	'.',	35,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (137,	'.',	35,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (138,	'.',	35,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (139,  'Highly Valuable',	35,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (140,  'Numeric',	36	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (141,  'Value',	37	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (142,  'Value',	38	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (143,  'Value',	39	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (144,  'Value',	40	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (145,	'Definitely not purchase it',	41,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (146,	'Probably not purchase it',	41,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (147,	'Might or might not purchase it',   41,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (148,	'Probably purchase it',	41,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (149,	'Definitely purchase it',	41,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (150,	'Definitely not purchase it',	42,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (151,	'Probably not purchase it',	42,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (152,	'Might or might not purchase it',	42,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (153,	'Probably purchase it',	42,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (154,	'Definitely purchase it',	42,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (155,	'Limited Value',	43,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (156,	'.',	43,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (157,	'.',	43,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (158,	'.',	43,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (159,	'.',	43,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (160,	'.',	43,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (161,	'.',	43,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (162,	'.',	43,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (163,	'.',	43,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (164,	'Highly Valuable',	43,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (165,	'Limited Value',	44,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (166,	'.',	44,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (167,	'.',	44,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (168,	'.',	44,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (169,	'.',	44,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (170,	'.',	44,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (171,	'.',	44,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (172,	'.',	44,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (173,	'.',	44,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (174,  'Highly Valuable',	44,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (175,  'Numeric',	45	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (176,  'Value',	46	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (177,  'Value',	47	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (178,  'Value',	48	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (179,  'Value',	49	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (180,	'Definitely not purchase it',	50,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (181,	'Probably not purchase it',	50,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (182,	'Might or might not purchase it',   50,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (183,	'Probably purchase it',	50,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (184,	'Definitely purchase it',	50,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (185,	'Definitely not purchase it',	51,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (186,	'Probably not purchase it',	51,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (187,	'Might or might not purchase it',	51,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (188,	'Probably purchase it',	51,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (189,	'Definitely purchase it',	51,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (190,	'Limited Value',	52,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (191,	'.',	52,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (192,	'.',	52,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (193,	'.',	52,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (194,	'.',	52,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (195,	'.',	52,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (196,	'.',	52,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (197,	'.',	52,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (198,	'.',	52,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (199,	'Highly Valuable',	52,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (200,	'Limited Value',	53,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (201,	'.',	53,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (202,	'.',	53,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (203,	'.',	53,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (204,	'.',	53,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (205,	'.',	53,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (206,	'.',	53,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (207,	'.',	53,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (208,	'.',	53,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (209,  'Highly Valuable',	53,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (210,  'Numeric',	54	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (211,  'Value',	55	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (212,  'Value',	56	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (213,  'Value',	57	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (214,  'Value',	58	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (215,	'Definitely not purchase it',	59,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (216,	'Probably not purchase it',	59,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (217,	'Might or might not purchase it',   59,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (218,	'Probably purchase it',	59,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (219,	'Definitely purchase it',	59,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (220,	'Definitely not purchase it',	60,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (221,	'Probably not purchase it',	60,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (222,	'Might or might not purchase it',	60,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (223,	'Probably purchase it',	60,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (224,	'Definitely purchase it',	60,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (225,	'Limited Value',	61,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (226,	'.',	61,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (227,	'.',	61,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (228,	'.',	61,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (229,	'.',	61,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (230,	'.',	61,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (231,	'.',	61,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (232,	'.',	61,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (233,	'.',	61,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (234,	'Highly Valuable',	61,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (235,	'Limited Value',	62,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (236,	'.',	62,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (237,	'.',	62,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (238,	'.',	62,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (239,	'.',	62,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (240,	'.',	62,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (241,	'.',	62,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (242,	'.',	62,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (243,	'.',	62,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (244,  'Highly Valuable',	62,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (245,  'Numeric',	63	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (246,  'Value',	64	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (247,  'Value',	65	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (248,  'Value',	66	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (249,  'Value',	67	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (250,	'Definitely not purchase it',	68,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (251,	'Probably not purchase it',	68,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (252,	'Might or might not purchase it',   68,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (253,	'Probably purchase it',	68,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (254,	'Definitely purchase it',	68,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (255,	'Definitely not purchase it',	69,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (256,	'Probably not purchase it',	69,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (257,	'Might or might not purchase it',	69,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (258,	'Probably purchase it',	69,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (259,	'Definitely purchase it',	69,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (260,	'Limited Value',	70,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (261,	'.',	70,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (262,	'.',	70,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (263,	'.',	70,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (264,	'.',	70,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (265,	'.',	70,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (266,	'.',	70,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (267,	'.',	70,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (268,	'.',	70,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (269,	'Highly Valuable',	70,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (270,	'Limited Value',	71,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (271,	'.',	71,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (272,	'.',	71,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (273,	'.',	71,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (274,	'.',	71,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (275,	'.',	71,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (276,	'.',	71,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (277,	'.',	71,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (278,	'.',	71,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (279,  'Highly Valuable',	71,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (280,  'Numeric',	72	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (281,  'Value',	73	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (282,  'Value',	74	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (283,  'Value',	75	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (284,  'Value',	76	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (285,	'Definitely not purchase it',	77,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (286,	'Probably not purchase it',	77,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (287,	'Might or might not purchase it',   77,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (288,	'Probably purchase it',	77,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (289,	'Definitely purchase it',	77,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (290,	'Definitely not purchase it',	78,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (291,	'Probably not purchase it',	78,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (292,	'Might or might not purchase it',	78,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (293,	'Probably purchase it',	78,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (294,	'Definitely purchase it',	78,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (295,	'Limited Value',	79,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (296,	'.',	79,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (297,	'.',	79,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (298,	'.',	79,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (299,	'.',	79,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (300,	'.',	79,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (301,	'.',	79,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (302,	'.',	79,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (303,	'.',	79,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (304,	'Highly Valuable',	79,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (305,	'Limited Value',	80,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (306,	'.',	80,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (307,	'.',	80,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (308,	'.',	80,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (309,	'.',	80,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (310,	'.',	80,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (311,	'.',	80,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (312,	'.',	80,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (313,	'.',	80,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (314,  'Highly Valuable',	80,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (315,  'Numeric',	81	, null);

INSERT INTO public.option(id, "Text", "questionId", value) VALUES (316,  'Value',	82	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (317,  'Value',	83	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (318,  'Value',	84	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (319,  'Value',	85	, null);
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (320,	'Definitely not purchase it',	86,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (321,	'Probably not purchase it',	86,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (322,	'Might or might not purchase it',   86,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (323,	'Probably purchase it',	86,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (324,	'Definitely purchase it',	86,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (325,	'Definitely not purchase it',	87,	'0');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (326,	'Probably not purchase it',	87,	'0.1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (327,	'Might or might not purchase it',	87,	'0.3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (328,	'Probably purchase it',	87,	'0.5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (329,	'Definitely purchase it',	87,	'0.7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (330,	'Limited Value',	88,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (331,	'.',	88,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (332,	'.',	88,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (333,	'.',	88,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (334,	'.',	88,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (335,	'.',	88,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (336,	'.',	88,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (337,	'.',	88,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (338,	'.',	88,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (339,	'Highly Valuable',	88,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (340,	'Limited Value',	89,	'1');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (341,	'.',	89,	'2');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (342,	'.',	89,	'3');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (343,	'.',	89,	'4');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (344,	'.',	89,	'5');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (345,	'.',	89,	'6');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (346,	'.',	89,	'7');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (347,	'.',	89,	'8');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (348,	'.',	89,	'9');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (349,  'Highly Valuable',	8,	'10');
INSERT INTO public.option(id, "Text", "questionId", value) VALUES (350,  'Numeric',	81	, null);